import React from 'react'
import * as NextHead from 'next/head'

interface Props {
  title?: string
}

const Head: React.FC<Props> = ({ title }) => {
  const DEFAULT_TITLE = 'Create Next App'
  return (
    <NextHead.default>
      <title>{title ?? DEFAULT_TITLE}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead.default>
  )
}

export default Head
